# Základní konfigurace aplikace
spring.application.name=portfolio

# Port serveru
server.port=8080

# Povolení detailních chybových hlášek v dev módu
server.error.include-message=always
server.error.include-binding-errors=always

# Logování
logging.level.com.ondrecreates.portfolio=DEBUG
